name: Compress and Publish Release

on:
  push:
    branches:
      - main  # Cambia esto al nombre de tu rama principal si es diferente

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get module version from module.prop
      id: get_version
      run: |
        version=$(grep -oP '(?<=version=).+' module.prop)
        echo "Module version: $version"
        echo "::set-output name=version::$version"

    - name: Create ZIP archive
      run: |
        zip -r repo.zip disablecamerasoundsmiui13

    - name: Upload ZIP archive
      uses: actions/upload-artifact@v2
      with:
        name: repository-archive
        path: repo.zip

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v${{ steps.get_version.outputs.version }}  # Usamos la versión extraída
        release_name: Release v${{ steps.get_version.outputs.version }}  # Usamos la versión extraída
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: repo.zip
        asset_name: repo.zip
        asset_content_type: application/zip
