name: Create Release and Upload Zip

on:
  workflow_dispatch: # This allows manually triggering the workflow from the "Run workflow" button on the repository page

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      
    - name: Set Up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16 # Use Node.js version 16

    - name: Install Dependencies
      run: |
        npm install -g zip-cli
        npm install axios

    - name: Get Version from module.prop
      id: get_version
      run: |
        version_line=$(grep -oP 'version=\K[^"]+' module.prop)
        echo "VERSION=${version_line}" >> $GITHUB_ENV

    - name: Create Zip Archive
      run: zip -r repo.zip .

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        RELEASE_VERSION: ${{ env.VERSION }} # Use the environment variable directly in the inputs
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./repo.zip
        asset_name: repo.zip
        asset_content_type: application/zip
