name: Create Release and Upload Zip

on:
  workflow_dispatch: # Esto permitirá ejecutar manualmente el flujo de trabajo desde el botón de "Run workflow" en la página del repositorio

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v2
      
    - name: Set Up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Get Version from module.prop
      id: get_version
      run: |
        version_line=$(grep -oP 'version=\K[^"]+' module.prop)
        echo "::set-output name=version::$version_line"

    - name: Create Zip Archive
      run: zip -r repo.zip .

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        release_name: Release ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./repo.zip
        asset_name: repo.zip
        asset_content_type: application/zip
